---
- name: download bat [armhf]
  get_url:
    url: '{{ bat_redis_url_armhf }}'
    checksum: 'sha256:{{ bat_redis_armhf_sha256sum }}'
    dest: '{{ bat_download_dir }}/{{ bat_redis_armhf_filename }}'
    force: no
    mode: 'u=rw,go=r'
  when:
    - ansible_architecture[:3] == "arm"
    - ansible_userspace_bits == '32'
    - ansible_os_family == "Debian"

- name: install bat [armhf]
  become: yes
  apt:
    deb: '{{ bat_download_dir }}/{{ bat_redis_armhf_filename }}'
  when:
    - ansible_architecture[:3] == "arm"
    - ansible_userspace_bits == '32'
    - ansible_os_family == "Debian"
