---
- name: download bat [arm64]
  get_url:
    url: '{{ bat_redis_url_arm64 }}'
    checksum: 'sha256:{{ bat_redis_arm64_sha256sum }}'
    dest: '{{ bat_download_dir }}/{{ bat_redis_arm64_filename }}'
    force: no
    mode: 'u=rw,go=r'
  when:
    - ansible_architecture[:3] == "arm"
    - ansible_userspace_bits == '64'
    - ansible_os_family == "Debian"

- name: install bat [arm64]
  become: yes
  apt:
    deb: '{{ bat_download_dir }}/{{ bat_redis_arm64_filename }}'
  when:
    - ansible_architecture[:3] == "arm"
    - ansible_userspace_bits == '64'
    - ansible_os_family == "Debian"
