---
- include_tasks: debug_output.yml

- name: create download directory
  file:
    state: directory
    mode: 'u==rwx,go==rx'
    dest: '{{ bat_download_dir }}'

- include_tasks: debian_amd64.yml
  when:
    - ansible_architecture == "x86_64"
    - ansible_os_family == "Debian"
    - ansible_userspace_bits == '64'

- include_tasks: debian_arm64.yml
  when:
    - ansible_architecture[:3] == "arm"
    - ansible_userspace_bits == '64'
    - ansible_os_family == "Debian"

- include_tasks: debian_armhf.yml
  when:
    - ansible_architecture[:3] == "arm"
    - ansible_userspace_bits == '32'
    - ansible_os_family == "Debian"
